patches-source = "bearinmindcat/morphe-patches"
brand = "bearinmindcat"

[GoogleMaps-bearinmindcat]
enabled = true
pkg-name = "com.google.android.apps.maps"
app-name = "Google Maps"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/maps"
uptodown-dlurl = "https://google-maps.en.uptodown.com/android/download"
apkpure-dlurl = "https://apkpure.com/google-maps-app/com.google.android.apps.maps"
apkcombo-dlurl = "https://apkcombo.com/google-maps/com.google.android.apps.maps"



