patches-source = "brosssh/morphe-patches"
brand = "brosssh"

[komoot-brosssh]
enabled = true
pkg-name = "de.komoot.android"
app-name = "Komoot"
apkmirror-dlurl = "https://www.apkmirror.com/apk/komoot-gmbh/komoot-cycling-hiking-mountain-biking-maps"
uptodown-dlurl = "https://komoot.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/komoot-hike-bike-run/de.komoot.android"


