enable-module-update = true
patches-source = "browzomje/browzomje-patches"
patch-brand = "Browzomje"
cli-type = "morphe"

[Pinterest-Morphe-Browzomje]
enabled = true
app-name = "Pinterest"
pkg-name = "com.pinterest"
uptodown-dlurl = "https://pinterest.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pinterest/pinterest-one-destination-for-a-world-of-inspiration"

[Pinterest-Morphe-Browzomje-Experimental]
enabled = true
app-name = "Pinterest"
sub-variant = "Experimental"
pkg-name = "com.pinterest"
version = "latest"
skip-patch-app-check = true
uptodown-dlurl = "https://pinterest.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pinterest/pinterest-one-destination-for-a-world-of-inspiration"
