patches-source = "bufferk/morphe-patches"
brand = "bufferk"

[Medium-bufferk]
enabled = true
pkg-name = "com.medium.reader"
app-name = "Medium"
apkmirror-dlurl = "https://www.apkmirror.com/apk/a-medium-corporation/medium"
uptodown-dlurl = "https://medium.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/medium/com.medium.reader"
apkcombo-dlurl = "https://apkcombo.com/medium/com.medium.reader"
