patches-source = "RookieEnough/De-Vanced"
brand = "DeVanced"

[GoogleRecorder-DeVanced]
enabled = true
pkg-name = "com.google.android.apps.recorder"
app-name = "Google Recorder"
build-mode = "both"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-recorder/"
uptodown-dlurl = "https://opnemer.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.recorder"

[MicrosoftLens-DeVanced]
enabled = true
pkg-name = "com.microsoft.office.officelens"
app-name = "Microsoft Lens"
apkmirror-dlurl = "https://www.apkmirror.com/apk/microsoft-corporation/microsoft-lens-pdf-scanner"
uptodown-dlurl = "https://office-lens.en.uptodown.com/android"

[Photomath-DeVanced]
enabled = true
pkg-name = "com.microblink.photomath"
app-name = "Photomath"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath"
uptodown-dlurl = "https://photomath.en.uptodown.com/android"

[Viber-DeVanced]
enabled = true
pkg-name = "com.viber.voip"
app-name = "Viber"
apkmirror-dlurl = "https://www.apkmirror.com/apk/viber-media-s-a-r-l/viber"
archive-dlurl = "https://archive.org/download/geologically/apks/com.viber.voip"

[Strava-DeVanced]
enabled = true
pkg-name = "com.strava"
app-name = "Strava"
apkcombo-dlurl = "https://apkcombo.com/it/strava/com.strava"



