[Facebook-Froggo]
enabled = true
pkg-name = "com.facebook.katana"
app-name = "Facebook"
patches-source = "SapitoSucio/FroggoMorphePatches"
brand = "Froggo"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/facebook-app/com.facebook.katana"
apkcombo-dlurl = "https://apkcombo.com/facebook/com.facebook.katana"

[Facebook-andrewliang25]
enabled = true
pkg-name = "com.facebook.katana"
app-name = "Facebook"
patches-source = "andrewliang25/morphe-patches"
brand = "andrewliang25"
included-patches = "'[General] AMOLED black theme' '[Reels] Download any reel'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/facebook-app/com.facebook.katana"
apkcombo-dlurl = "https://apkcombo.com/facebook/com.facebook.katana"

[Facebook-HushFacebook]
enabled = true
pkg-name = "com.facebook.katana"
app-name = "Facebook"
patches-source = "SysAdminDoc/HushFacebook"
brand = "HushFacebook"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/facebook-app/com.facebook.katana"
apkcombo-dlurl = "https://apkcombo.com/facebook/com.facebook.katana"

[Facebook-DeVanced]
enabled = true
pkg-name = "com.facebook.katana"
app-name = "Facebook"
patches-source = "RookieEnough/De-Vanced"
brand = "DeVanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/facebook-app/com.facebook.katana"
apkcombo-dlurl = "https://apkcombo.com/facebook/com.facebook.katana"
