enable-module-update = true
cli-type = "morphe"
patch-brand = "Hoodles-Stylus"
patches-source = "'hoo-dles/morphe-patches' 'ch3thanhs/stylus'"

[GitHub-Morphe-Hoodles-Stylus]
enabled = true
app-name = "GitHub"
pkg-name = "com.github.android"
included-patches = "'AMOLED dark theme' | 'Force system font (including monospace) (GitHub)'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/github/github-2"
apkmirror-example-url = "https://www.apkmirror.com/apk/github/github-2/github-1-202-0-release/"

[GitHub-Morphe-Hoodles-Stylus-Experimental]
enabled = true
app-name = "GitHub"
pkg-name = "com.github.android"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
included-patches = "'AMOLED dark theme' | 'Force system font (including monospace) (GitHub)'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/github/github-2"
apkmirror-example-url = "https://www.apkmirror.com/apk/github/github-2/github-1-202-0-release/"
