[FairEmail-heval99]
enabled = true
pkg-name = "eu.faircode.email"
app-name = "FairEmail"
brand = "heval99"
patches-source = "heval99/Heval-Morphe-Patches"
uptodown-dlurl = "https://fairemail.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/marcel-bokhorst/fairemail-open-source-privacy-oriented-email"
apkpure-dlurl = "https://apkpure.com/fairemail-privacy-aware-email/eu.faircode.email"
apkcombo-dlurl = "https://apkcombo.com/fairemail-privacy-aware-email/eu.faircode.email"

[FairEmail-heval99-Experimental]
enabled = true
app-name = "FairEmail"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "eu.faircode.email"
patches-source = "heval99/Heval-Morphe-Patches"
brand = "heval99"
apkmirror-dlurl = "https://www.apkmirror.com/apk/marcel-bokhorst/fairemail-open-source-privacy-oriented-email"
uptodown-dlurl = "https://fairemail.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/fairemail-privacy-aware-email/eu.faircode.email"
apkcombo-dlurl = "https://apkcombo.com/fairemail-privacy-aware-email/eu.faircode.email"
