enable-module-update = true
patches-source = "hoo-dles/morphe-patches"
patch-brand = "Hoodles"
cli-type = "morphe"

[Duolingo-hoodles]
enabled = true
pkg-name = "com.duolingo"
app-name = "Duolingo"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/duolingo-learn-languages/com.duolingo"
apkcombo-dlurl = "https://apkcombo.com/duolingo/com.duolingo"
[WPSOffice-hoodles]
enabled = true
pkg-name = "cn.wps.moffice_eng"
app-name = "WPS Office"
apkmirror-dlurl = "https://www.apkmirror.com/apk/wps-software-pte-ltd/wps-office-pdf"
uptodown-dlurl = "https://wps-office.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/wps-office-pdf-word-excel-ppt/cn.wps.moffice_eng"
apkcombo-dlurl = "https://apkcombo.com/wps-office/cn.wps.moffice_eng"
[Wallcraft-hoodles]
enabled = true
pkg-name = "com.wallpaperscraft.wallpaper"
app-name = "Wallcraft"
apkmirror-dlurl = "https://www.apkmirror.com/apk/nebuchadnezzar-doo/wallpapers-hd-4k-backgrounds"
uptodown-dlurl = "https://wallpaperscraft.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/wallpaper-4k-hd-%E2%80%93-wallcraft/com.wallpaperscraft.wallpaper"
apkcombo-dlurl = "https://apkcombo.com/wallpaper-4k-hd-wallcraft/com.wallpaperscraft.wallpaper"
[SolidExplorer-hoodles]
enabled = true
pkg-name = "pl.solidexplorer2"
app-name = "Solid Explorer"
apkmirror-dlurl = "https://www.apkmirror.com/apk/lmicp/solid-explorer-file-manager"
uptodown-dlurl = "https://solid-explorer-file-manager.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/solid-explorer-file-manager/pl.solidexplorer2"
apkcombo-dlurl = "https://apkcombo.com/solid-explorer/pl.solidexplorer2"
[IconPacker-hoodles]
enabled = true
pkg-name = "cn.ommiao.iconpacker"
app-name = "Icon Packer"
apkpure-dlurl = "https://apkpure.com/icon-packer/cn.ommiao.iconpacker"
apkcombo-dlurl = "https://apkcombo.com/icon-packer/cn.ommiao.iconpacker"
archive-dlurl = "https://archive.org/download/geologically/apks/cn.ommiao.iconpacker"
[PodcastAddict-hoodles]
enabled = true
pkg-name = "com.bambuna.podcastaddict"
app-name = "Podcast Addict"
apkmirror-dlurl = "https://www.apkmirror.com/apk/xavier-guillemane/podcast-addict"
uptodown-dlurl = "https://podcast-addict.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/podcast-addict-app/com.bambuna.podcastaddict"
apkcombo-dlurl = "https://apkcombo.com/podcast-addict-podcast-player/com.bambuna.podcastaddict"
archive-dlurl = "https://archive.org/download/geologically/apks/com.bambuna.podcastaddict"
[SmartLauncher6-hoodles]
enabled = true
pkg-name = "ginlemon.flowerfree"
app-name = "Smart Launcher 6"
patch-folder = "smartlauncher"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/smart-launcher"
uptodown-dlurl = "https://smart-launcher.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/smart-launcher-6/ginlemon.flowerfree"
apkcombo-dlurl = "https://apkcombo.com/smart-launcher-6-%E2%80%A7-home-screen/ginlemon.flowerfree"
archive-dlurl = "https://archive.org/download/geologically/apks/ginlemon.flowerfree"
[MerriamWebsterDictionary-hoodles]
enabled = true
pkg-name = "com.merriamwebster"
app-name = "Merriam Webster Dictionary"
patch-folder = "webster"
apkmirror-dlurl = "https://www.apkmirror.com/apk/merriam-webster-inc/dictionary-merriam-webster"
apkpure-dlurl = "https://apkpure.com/dictionary-merriam-webster/com.merriamwebster"
apkcombo-dlurl = "https://apkcombo.com/dictionary-merriam-webster/com.merriamwebster"
uptodown-dlurl = "https://merriam-webster-dictionary.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/geologically/apks/com.merriamwebster"
[Pandora-hoodles]
enabled = true
pkg-name = "com.pandora.android"
app-name = "Pandora"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pandora/pandora-music-podcasts"
apkcombo-dlurl = "https://apkcombo.com/pandora/com.pandora.android"
archive-dlurl = "https://archive.org/download/geologically/apks/com.pandora.android"
[XRecorder-hoodles]
enabled = true
pkg-name = "videoeditor.videorecorder.screenrecorder"
app-name = "XRecorder"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshot-inc-2/screen-recorder-video-recorder-xrecorder"
apkpure-dlurl = "https://apkpure.com/screen-recorder-xrecorder-app/videoeditor.videorecorder.screenrecorder"
apkcombo-dlurl = "https://apkcombo.com/xrecorder/videoeditor.videorecorder.screenrecorder"
uptodown-dlurl = "https://videoeditor-videorecorder-screenrecorder.en.uptodown.com/android"
[NovaLauncher-hoodles]
enabled = true
pkg-name = "com.teslacoilsw.launcher"
app-name = "Nova Launcher"
patch-folder = "nova"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instabridge-sweden-ab/nova-launcher"
uptodown-dlurl = "https://nova-launcher.en.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/nova-launcher-home-screen/com.teslacoilsw.launcher"
apkpure-dlurl = "https://apkpure.com/nova-launcher-home-screen/com.teslacoilsw.launcher"
archive-dlurl = "https://archive.org/download/geologically/apks/com.teslacoilsw.launcher"
[Ventusky-hoodles]
enabled = true
pkg-name = "cz.ackee.ventusky"
app-name = "Ventusky"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ventusky/ventusky-weather-maps-radar"
uptodown-dlurl = "https://ventusky-weather-maps-and-radar.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/ventusky-weather-radar/cz.ackee.ventusky"
apkcombo-dlurl = "https://apkcombo.com/ventusky/cz.ackee.ventusky"
archive-dlurl = "https://archive.org/download/geologically/apks/cz.ackee.ventusky"
[CamScanner-hoodles]
enabled = true
pkg-name = "com.intsig.camscanner"
app-name = "CamScanner"
apkmirror-dlurl = "https://www.apkmirror.com/apk/intsig-pte/camscanner-phone-pdf-creator"
uptodown-dlurl = "https://camscanner-pdf-creator.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/camscanner-scanner-pdf-maker/com.intsig.camscanner"
apkcombo-dlurl = "https://apkcombo.com/camscanner/com.intsig.camscanner"
[GitHub-hoodles]
enabled = true
pkg-name = "com.github.android"
app-name = "GitHub"
included-patches = "'AMOLED dark theme'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/github/github-2"
uptodown-dlurl = "https://github-android.en.uptodown.com/android"
[HelloChinese-hoodles]
enabled = true
pkg-name = "com.hellochinese"
app-name = "HelloChinese"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/hellochinese-learn-chinese-mandarin/hellochinese-learn-chinese"
uptodown-dlurl = "https://hellochinese.en.uptodown.com/android"
[MyFitnessPal-hoodles]
enabled = true
pkg-name = "com.myfitnesspal.android"
app-name = "MyFitnessPal"
apkmirror-dlurl = "https://www.apkmirror.com/apk/myfitnesspal-inc/calorie-counter-myfitnesspal"
uptodown-dlurl = "https://calorie-counter-myfitnesspal.en.uptodown.com/android"
[PrimeVideo-hoodles]
enabled = true
pkg-name = "com.amazon.avod.thirdpartyclient"
app-name = "Prime Video"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/prime-video-android-tv/com.amazon.amazonvideo.livingroom"
apkcombo-dlurl = "https://apkcombo.com/prime-video/com.amazon.avod.thirdpartyclient"
[Goodreads-hoodles]
enabled = true
pkg-name = "com.goodreads"
app-name = "Goodreads"
apkmirror-dlurl = "https://www.apkmirror.com/apk/goodreads/goodreads"
uptodown-dlurl = "https://goodreads.en.uptodown.com/android"
[AdobeLightroom-hoodles]
enabled = true
pkg-name = "com.adobe.lrmobile"
app-name = "Adobe Lightroom"
patch-folder = "lightroom"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/geologically/apks/com.adobe.lrmobile"
[Xodo-hoodles]
enabled = true
pkg-name = "com.xodo.pdf.reader"
app-name = "Xodo"
apkmirror-dlurl = "https://www.apkmirror.com/apk/apryse-software-inc/xodo-pdf-reader-editor"
uptodown-dlurl = "https://xodo-docs.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/xodo-pdf-reader-editor/com.xodo.pdf.reader"
apkcombo-dlurl = "https://apkcombo.com/pdf-reader-editor-xodo/com.xodo.pdf.reader"
[CamScanner-Morphe-Hoodles]
enabled = true
app-name = "CamScanner"
arch = "all arm64-v8a"
pkg-name = "com.intsig.camscanner"
uptodown-dlurl = "https://camscanner-pdf-creator.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/intsig-pte/camscanner-phone-pdf-creator"
apkmirror-example-url = "https://www.apkmirror.com/apk/intsig-pte/camscanner-phone-pdf-creator/camscanner-scanner-pdf-maker-7-24-0-2608130000-release/"
apkpure-dlurl = "https://apkpure.com/camscanner-scanner-pdf-maker/com.intsig.camscanner"
apkcombo-dlurl = "https://apkcombo.com/camscanner/com.intsig.camscanner"
patcher-args = "--continue-on-error"
[PrimeVideo-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Prime Video"
sub-variant = "Experimental"
pkg-name = "com.amazon.avod.thirdpartyclient"
version = "latest"
skip-patch-app-check = true
arch = "arm64-v8a armeabi-v7a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"
[PrimeVideo-Morphe-Hoodles-Shared-Experimental]
enabled = true
app-name = "Prime Video"
variant = "Shared"
sub-variant = "Experimental"
pkg-name = "com.amazon.avod.thirdpartyclient"
version = "latest"
skip-patch-app-check = true
arch = "arm64-v8a armeabi-v7a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"
excluded-patches = "'Rename Shared Permissions'"
[XRecorder-Morphe-Hoodles]
enabled = true
app-name = "XRecorder"
arch = "all arm64-v8a armeabi-v7a"
pkg-name = "videoeditor.videorecorder.screenrecorder"
uptodown-dlurl = "https://videoeditor-videorecorder-screenrecorder.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshot-inc-2/screen-recorder-video-recorder-xrecorder"
[XRecorder-Morphe-Hoodles-Experimental]
enabled = true
app-name = "XRecorder"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
arch = "all arm64-v8a armeabi-v7a"
pkg-name = "videoeditor.videorecorder.screenrecorder"
uptodown-dlurl = "https://videoeditor-videorecorder-screenrecorder.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshot-inc-2/screen-recorder-video-recorder-xrecorder"
[SmartLauncher-Morphe-Hoodles]
enabled = true
app-name = "Smart Launcher"
pkg-name = "ginlemon.flowerfree"
uptodown-dlurl = "https://smart-launcher.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/smart-launcher"
[SmartLauncher-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Smart Launcher"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
pkg-name = "ginlemon.flowerfree"
uptodown-dlurl = "https://smart-launcher.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/smart-launcher"
[SmartLauncher6-Morphe-Hoodles]
enabled = true
app-name = "Smart Launcher 6"
pkg-name = "ginlemon.flowerfree"
uptodown-dlurl = "https://smart-launcher.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/smart-launcher"
[SmartLauncher6-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Smart Launcher 6"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
pkg-name = "ginlemon.flowerfree"
uptodown-dlurl = "https://smart-launcher.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/smart-launcher"
[NovaLauncher-Morphe-Hoodles]
enabled = true
app-name = "Nova Launcher"
arch = "all arm64-v8a armeabi-v7a"
pkg-name = "com.teslacoilsw.launcher"
uptodown-dlurl = "https://nova-launcher.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instabridge-sweden-ab/nova-launcher"
[NovaLauncher-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Nova Launcher"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
arch = "all arm64-v8a armeabi-v7a"
pkg-name = "com.teslacoilsw.launcher"
uptodown-dlurl = "https://nova-launcher.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instabridge-sweden-ab/nova-launcher"
[Xodo-Morphe-Hoodles]
enabled = true
app-name = "Xodo PDF"
arch = "arm64-v8a x86_64 armeabi-v7a x86"
pkg-name = "com.xodo.pdf.reader"
uptodown-dlurl = "https://xodo-pdf-reader-editor.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/xodo-technologies-inc/xodo-pdf-reader-editor"
[Xodo-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Xodo PDF"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
arch = "arm64-v8a x86_64 armeabi-v7a x86"
pkg-name = "com.xodo.pdf.reader"
uptodown-dlurl = "https://xodo-pdf-reader-editor.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/xodo-technologies-inc/xodo-pdf-reader-editor"
[SolidExplorer-Morphe-Hoodles]
enabled = true
app-name = "Solid Explorer"
pkg-name = "pl.solidexplorer2"
uptodown-dlurl = "https://solid-explorer-file-manager.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/lmicp/solid-explorer-file-manager"
[SolidExplorer-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Solid Explorer"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
pkg-name = "pl.solidexplorer2"
uptodown-dlurl = "https://solid-explorer-file-manager.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/lmicp/solid-explorer-file-manager"
[Wallcraft-Morphe-Hoodles]
enabled = true
app-name = "Wallcraft"
pkg-name = "com.wallpaperscraft.wallpaper"
uptodown-dlurl = "https://wallpaperscraft.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/nebuchadnezzar-doo/wallpapers-hd-4k-backgrounds"
[Wallcraft-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Wallcraft"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
pkg-name = "com.wallpaperscraft.wallpaper"
uptodown-dlurl = "https://wallpaperscraft.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/nebuchadnezzar-doo/wallpapers-hd-4k-backgrounds"
[WPSOffice-Morphe-Hoodles]
enabled = true
app-name = "WPS Office"
arch = "arm64-v8a armeabi-v7a"
pkg-name = "cn.wps.moffice_eng"
uptodown-dlurl = "https://wps-office.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/wps-software-pte-ltd/wps-office-pdf/"
[PodcastAddict-Morphe-Hoodles]
enabled = true
app-name = "Podcast Addict"
pkg-name = "com.bambuna.podcastaddict"
uptodown-dlurl = "https://podcast-addict.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/xavier-guillemane/podcast-addict"
[PodcastAddict-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Podcast Addict"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
pkg-name = "com.bambuna.podcastaddict"
uptodown-dlurl = "https://podcast-addict.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/xavier-guillemane/podcast-addict"
[MerriamWebsterDictionary-Morphe-Hoodles]
enabled = true
app-name = "Merriam-Webster Dictionary"
pkg-name = "com.merriamwebster"
uptodown-dlurl = "https://merriam-webster.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/merriam-webster-inc/dictionary-merriam-webster"
[Pandora-Morphe-Hoodles]
enabled = true
app-name = "Pandora"
pkg-name = "com.pandora.android"
uptodown-dlurl = "https://pandora.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pandora/pandora-music-podcasts"
[Ventusky-Morphe-Hoodles]
enabled = true
app-name = "Ventusky"
pkg-name = "cz.ackee.ventusky"
uptodown-dlurl = "https://ventusky-weather-maps-and-radar.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ventusky/ventusky-weather-maps-radar"
[Ventusky-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Ventusky"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
pkg-name = "cz.ackee.ventusky"
uptodown-dlurl = "https://ventusky-weather-maps-and-radar.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ventusky/ventusky-weather-maps-radar"
[NiagaraLauncher-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Niagara Launcher"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
pkg-name = "bitpit.launcher"
uptodown-dlurl = "https://niagara-launcher.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mellowdrop-studio/niagara-launcher-%f0%9f%94%b9-fresh-clean"
[HelloChinese-Morphe-Hoodles]
enabled = true
app-name = "HelloChinese"
arch = "arm64-v8a"
pkg-name = "com.hellochinese"
uptodown-dlurl = "https://hellochinese.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/hellochinese-learn-chinese-mandarin/hellochinese-learn-chinese/"
[MyFitnessPal-Morphe-Hoodles]
enabled = true
app-name = "MyFitnessPal"
pkg-name = "com.myfitnesspal.android"
uptodown-dlurl = "https://calorie-counter-myfitnesspal.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/myfitnesspal-inc/calorie-counter-myfitnesspal"
[MyFitnessPal-Morphe-Hoodles-Experimental]
enabled = true
app-name = "MyFitnessPal"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
pkg-name = "com.myfitnesspal.android"
uptodown-dlurl = "https://calorie-counter-myfitnesspal.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/myfitnesspal-inc/calorie-counter-myfitnesspal"
[Goodreads-Morphe-Hoodles]
enabled = true
app-name = "Goodreads"
pkg-name = "com.goodreads"
uptodown-dlurl = "https://goodreads.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/goodreads/goodreads"
[Goodreads-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Goodreads"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
pkg-name = "com.goodreads"
uptodown-dlurl = "https://goodreads.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/goodreads/goodreads"
[AdobeLightroom-Morphe-Hoodles]
enabled = true
app-name = "Adobe Lightroom"
arch = "arm64-v8a"
pkg-name = "com.adobe.lrmobile"
uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/adobe-lightroom/"
[Duolingo-Morphe-Hoodles]
enabled = true
app-name = "Duolingo"
pkg-name = "com.duolingo"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo"
