patches-source = "hoo-dles/morphe-patches"
brand = "hoodles"

[Duolingo-Morphe-Hoodles]
enabled = true
app-name = "Duolingo"
pkg-name = "com.duolingo"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo"

[WPSOffice-Morphe-Hoodles]
enabled = true
app-name = "WPS Office"
arch = "arm64-v8a armeabi-v7a"
pkg-name = "cn.wps.moffice_eng"
uptodown-dlurl = "https://wps-office.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/wps-software-pte-ltd/wps-office-pdf/"

[Wallcraft-Morphe-Hoodles]
enabled = true
app-name = "Wallcraft"
pkg-name = "com.wallpaperscraft.wallpaper"
uptodown-dlurl = "https://wallpaperscraft.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/nebuchadnezzar-doo/wallpapers-hd-4k-backgrounds"

[SolidExplorer-Morphe-Hoodles]
enabled = true
app-name = "Solid Explorer"
pkg-name = "pl.solidexplorer2"
uptodown-dlurl = "https://solid-explorer-file-manager.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/lmicp/solid-explorer-file-manager"

[IconPacker-hoodles]
enabled = true
pkg-name = "cn.ommiao.iconpacker"
app-name = "Icon Packer"
apkpure-dlurl = "https://apkpure.com/icon-packer/cn.ommiao.iconpacker"
apkcombo-dlurl = "https://apkcombo.com/icon-packer/cn.ommiao.iconpacker"
archive-dlurl = "https://archive.org/download/geologically/apks/cn.ommiao.iconpacker"

[PodcastAddict-Morphe-Hoodles]
enabled = true
app-name = "Podcast Addict"
pkg-name = "com.bambuna.podcastaddict"
uptodown-dlurl = "https://podcast-addict.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/xavier-guillemane/podcast-addict"

[SmartLauncher6-Morphe-Hoodles]
enabled = true
app-name = "Smart Launcher 6"
pkg-name = "ginlemon.flowerfree"
uptodown-dlurl = "https://smart-launcher.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/smart-launcher"

[MerriamWebsterDictionary-Morphe-Hoodles]
enabled = true
app-name = "Merriam-Webster Dictionary"
pkg-name = "com.merriamwebster"
uptodown-dlurl = "https://merriam-webster.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/merriam-webster-inc/dictionary-merriam-webster"

[Pandora-Morphe-Hoodles]
enabled = true
app-name = "Pandora"
pkg-name = "com.pandora.android"
uptodown-dlurl = "https://pandora.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pandora/pandora-music-podcasts"

[XRecorder-Morphe-Hoodles]
enabled = true
app-name = "XRecorder"
arch = "all arm64-v8a armeabi-v7a"
pkg-name = "videoeditor.videorecorder.screenrecorder"
uptodown-dlurl = "https://videoeditor-videorecorder-screenrecorder.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshot-inc-2/screen-recorder-video-recorder-xrecorder"

[NovaLauncher-Morphe-Hoodles]
enabled = true
app-name = "Nova Launcher"
arch = "all arm64-v8a armeabi-v7a"
pkg-name = "com.teslacoilsw.launcher"
uptodown-dlurl = "https://nova-launcher.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instabridge-sweden-ab/nova-launcher"

[Ventusky-Morphe-Hoodles]
enabled = true
app-name = "Ventusky"
pkg-name = "cz.ackee.ventusky"
uptodown-dlurl = "https://ventusky-weather-maps-and-radar.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ventusky/ventusky-weather-maps-radar"

[CamScanner-Morphe-Hoodles]
enabled = true
app-name = "CamScanner"
arch = "all arm64-v8a"
pkg-name = "com.intsig.camscanner"
uptodown-dlurl = "https://camscanner-pdf-creator.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/intsig-pte/camscanner-phone-pdf-creator"
apkmirror-example-url = "https://www.apkmirror.com/apk/intsig-pte/camscanner-phone-pdf-creator/camscanner-scanner-pdf-maker-7-24-0-2608130000-release/"
apkpure-dlurl = "https://apkpure.com/camscanner-scanner-pdf-maker/com.intsig.camscanner"
apkcombo-dlurl = "https://apkcombo.com/camscanner/com.intsig.camscanner"
patcher-args = "--continue-on-error"

[GitHub-hoodles]
enabled = true
pkg-name = "com.github.android"
app-name = "GitHub"
included-patches = "'AMOLED dark theme'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/github/github-2"
uptodown-dlurl = "https://github-android.en.uptodown.com/android"

[HelloChinese-Morphe-Hoodles]
enabled = true
app-name = "HelloChinese"
arch = "arm64-v8a"
pkg-name = "com.hellochinese"
uptodown-dlurl = "https://hellochinese.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/hellochinese-learn-chinese-mandarin/hellochinese-learn-chinese/"

[MyFitnessPal-Morphe-Hoodles]
enabled = true
app-name = "MyFitnessPal"
pkg-name = "com.myfitnesspal.android"
uptodown-dlurl = "https://calorie-counter-myfitnesspal.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/myfitnesspal-inc/calorie-counter-myfitnesspal"

[PrimeVideo-hoodles]
enabled = true
pkg-name = "com.amazon.avod.thirdpartyclient"
app-name = "Prime Video"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/prime-video-android-tv/com.amazon.amazonvideo.livingroom"
apkcombo-dlurl = "https://apkcombo.com/prime-video/com.amazon.avod.thirdpartyclient"

[Goodreads-Morphe-Hoodles]
enabled = true
app-name = "Goodreads"
pkg-name = "com.goodreads"
uptodown-dlurl = "https://goodreads.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/goodreads/goodreads"

[AdobeLightroom-Morphe-Hoodles]
enabled = true
app-name = "Adobe Lightroom"
arch = "arm64-v8a"
pkg-name = "com.adobe.lrmobile"
uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/adobe-lightroom/"

[Xodo-Morphe-Hoodles]
enabled = true
app-name = "Xodo PDF"
arch = "arm64-v8a x86_64 armeabi-v7a x86"
pkg-name = "com.xodo.pdf.reader"
uptodown-dlurl = "https://xodo-pdf-reader-editor.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/xodo-technologies-inc/xodo-pdf-reader-editor"

[GitHub-Morphe-Hoodles-Stylus]
enabled = true
app-name = "GitHub"
pkg-name = "com.github.android"
included-patches = "'AMOLED dark theme' | 'Force system font (including monospace) (GitHub)'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/github/github-2"
apkmirror-example-url = "https://www.apkmirror.com/apk/github/github-2/github-1-202-0-release/"

[GitHub-Morphe-Hoodles-Stylus-Experimental]
enabled = true
app-name = "GitHub"
pkg-name = "com.github.android"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
included-patches = "'AMOLED dark theme' | 'Force system font (including monospace) (GitHub)'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/github/github-2"
apkmirror-example-url = "https://www.apkmirror.com/apk/github/github-2/github-1-202-0-release/"

[PrimeVideo-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Prime Video"
sub-variant = "Experimental"
pkg-name = "com.amazon.avod.thirdpartyclient"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
arch = "arm64-v8a armeabi-v7a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"

[PrimeVideo-Morphe-Hoodles-Shared-Experimental]
enabled = true
app-name = "Prime Video"
variant = "Shared"
sub-variant = "Experimental"
pkg-name = "com.amazon.avod.thirdpartyclient"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
arch = "arm64-v8a armeabi-v7a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"
excluded-patches = "'Rename Shared Permissions'"

[XRecorder-Morphe-Hoodles-Experimental]
enabled = true
app-name = "XRecorder"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
arch = "all arm64-v8a armeabi-v7a"
pkg-name = "videoeditor.videorecorder.screenrecorder"
uptodown-dlurl = "https://videoeditor-videorecorder-screenrecorder.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshot-inc-2/screen-recorder-video-recorder-xrecorder"

[SmartLauncher-Morphe-Hoodles]
enabled = true
app-name = "Smart Launcher"
pkg-name = "ginlemon.flowerfree"
uptodown-dlurl = "https://smart-launcher.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/smart-launcher"

[SmartLauncher6-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Smart Launcher 6"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "ginlemon.flowerfree"
uptodown-dlurl = "https://smart-launcher.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/smart-launcher"

[NovaLauncher-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Nova Launcher"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
arch = "all arm64-v8a armeabi-v7a"
pkg-name = "com.teslacoilsw.launcher"
uptodown-dlurl = "https://nova-launcher.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instabridge-sweden-ab/nova-launcher"

[Xodo-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Xodo PDF"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
arch = "arm64-v8a x86_64 armeabi-v7a x86"
pkg-name = "com.xodo.pdf.reader"
uptodown-dlurl = "https://xodo-pdf-reader-editor.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/xodo-technologies-inc/xodo-pdf-reader-editor"

[SolidExplorer-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Solid Explorer"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "pl.solidexplorer2"
uptodown-dlurl = "https://solid-explorer-file-manager.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/lmicp/solid-explorer-file-manager"

[Wallcraft-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Wallcraft"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "com.wallpaperscraft.wallpaper"
uptodown-dlurl = "https://wallpaperscraft.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/nebuchadnezzar-doo/wallpapers-hd-4k-backgrounds"

[PodcastAddict-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Podcast Addict"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "com.bambuna.podcastaddict"
uptodown-dlurl = "https://podcast-addict.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/xavier-guillemane/podcast-addict"

[Ventusky-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Ventusky"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "cz.ackee.ventusky"
uptodown-dlurl = "https://ventusky-weather-maps-and-radar.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ventusky/ventusky-weather-maps-radar"

[NiagaraLauncher-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Niagara Launcher"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "bitpit.launcher"
uptodown-dlurl = "https://niagara-launcher.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mellowdrop-studio/niagara-launcher-%f0%9f%94%b9-fresh-clean"

[MyFitnessPal-Morphe-Hoodles-Experimental]
enabled = true
app-name = "MyFitnessPal"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "com.myfitnesspal.android"
uptodown-dlurl = "https://calorie-counter-myfitnesspal.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/myfitnesspal-inc/calorie-counter-myfitnesspal"

[Goodreads-Morphe-Hoodles-Experimental]
enabled = true
app-name = "Goodreads"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "com.goodreads"
uptodown-dlurl = "https://goodreads.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/goodreads/goodreads"
