enable-module-update = true
patches-source = "arandomhooman/hoomans-morphe-patches"
patch-brand = "Hooman"
cli-type = "morphe"
[Symfonium-Morphe-Hooman]
enabled = true
app-name = "Symfonium"
pkg-name = "app.symfonik.music.player"
uptodown-dlurl = "https://symfonium.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tolriq/symfonium-music-player-cast"

[AdvancedDownloadManager-Morphe-Hooman]
enabled = true
app-name = "Advanced Download Manager"
pkg-name = "com.dv.adm"
uptodown-dlurl="https://advanced-download-manager.en.uptodown.com/android"
apkmirror-dlurl="https://www.apkmirror.com/apk/admtorrent/advanced-download-manager/"

[Twitch-Morphe-Hooman]
enabled = true
app-name = "Twitch"
pkg-name = "tv.twitch.android.app"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch"

[BatteryGuru-Morphe-Hooman]
enabled = true
app-name = "Battery Guru"
pkg-name = "com.paget96.batteryguru"
uptodown-dlurl = "https://battery-guru.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/paget96/battery-guru-health-saver/"

[BatteryGuru-Morphe-Hooman-Experimental]
enabled = true
app-name = "Battery Guru"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
pkg-name = "com.paget96.batteryguru"
uptodown-dlurl = "https://battery-guru.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/paget96/battery-guru-health-saver/"

[Poweramp-Morphe-Hooman]
enabled = true
app-name = "Poweramp"
arch = "arm64-v8a"
pkg-name = "com.maxmpz.audioplayer"
uptodown-dlurl = "https://poweramp-music-player.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/max-mp/poweramp/"
apkpure-dlurl = "https://apkpure.com/poweramp-music-player-trial-app/com.maxmpz.audioplayer"
apkcombo-dlurl = "https://apkcombo.com/poweramp/com.maxmpz.audioplayer"

[Poweramp-Morphe-Hooman-Experimental]
enabled = true
app-name = "Poweramp"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
arch = "arm64-v8a"
pkg-name = "com.maxmpz.audioplayer"
uptodown-dlurl = "https://poweramp-music-player.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/max-mp/poweramp/"
apkpure-dlurl = "https://apkpure.com/poweramp-music-player-trial-app/com.maxmpz.audioplayer"
apkcombo-dlurl = "https://apkcombo.com/poweramp/com.maxmpz.audioplayer"

[AdobeAcrobat-Morphe-Hooman]
enabled = true
app-name = "Adobe Acrobat"
arch = "all arm64-v8a x86_64"
pkg-name = "com.adobe.reader"
uptodown-dlurl = "https://adobe-reader.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/adobe-acrobat/"

[AdobeAcrobat-Morphe-Hooman-Experimental]
enabled = true
app-name = "Adobe Acrobat"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
arch = "all arm64-v8a x86_64"
pkg-name = "com.adobe.reader"
uptodown-dlurl = "https://adobe-reader.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/adobe-acrobat/"

[MicrosoftSwiftKey-Morphe-Hooman]
enabled = true
app-name = "Microsoft SwiftKey"
pkg-name = "com.touchtype.swiftkey"
skip-patch-app-check = true
uptodown-dlurl = "https://swiftkey-keyboard.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/swiftkey/swiftkey-keyboard"
