patches-source = "jasonwu1994/Gboard-patches"
patches-version = "both"
brand = "jasonwu1994"
arch = "arm64-v8a"

[Gboard-jasonwu1994]
enabled = true
pkg-name = "com.google.android.inputmethod.latin"
app-name = "Gboard"
build-mode = "both"
excluded-patches = "'Package Rename'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/gboard-the-google-keyboard-app/com.google.android.inputmethod.latin"
apkcombo-dlurl = "https://apkcombo.com/gboard/com.google.android.inputmethod.latin"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.inputmethod.latin"

[Gboard-jasonwu1994-Clone]
enabled = true
pkg-name = "com.google.android.inputmethod.latin"
app-name = "Gboard"
variant = "Clone"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/gboard-the-google-keyboard-app/com.google.android.inputmethod.latin"
apkcombo-dlurl = "https://apkcombo.com/gboard/com.google.android.inputmethod.latin"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.inputmethod.latin"



