patches-source = "kiraio-moe/Lain-Patches"
brand = "Lain"

[Hermit-Lain]
enabled = true
pkg-name = "com.chimbori.hermitcrab"
app-name = "Hermit"
patch-folder = "hermit"
apkmirror-dlurl = "https://www.apkmirror.com/apk/chimbori/hermit-lite-apps-browser"
uptodown-dlurl = "https://hermit.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/hermit-%E2%80%94-lite-apps-browser/com.chimbori.hermitcrab"
apkcombo-dlurl = "https://apkcombo.com/hermit-lite-apps-browser/com.chimbori.hermitcrab"

[Drofus-Lain]
enabled = true
app-name = "Drofus"
arch = "arm64-v8a armeabi-v7a"
pkg-name = "com.mixapplications.rufus"
uptodown-dlurl = "https://rufus-unofficial.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mixapplications/drofus-iso2usb"

[Hermit-Lain-Experimental]
enabled = true
app-name = "Hermit"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "com.chimbori.hermitcrab"
apkmirror-dlurl = "https://www.apkmirror.com/apk/chimbori/hermit-lite-apps-browser"
uptodown-dlurl = "https://hermit.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/hermit-%E2%80%94-lite-apps-browser/com.chimbori.hermitcrab"
apkcombo-dlurl = "https://apkcombo.com/hermit-lite-apps-browser/com.chimbori.hermitcrab"

[Drofus-Lain-Experimental]
enabled = true
app-name = "Drofus"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
arch = "arm64-v8a armeabi-v7a"
pkg-name = "com.mixapplications.rufus"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mixapplications/drofus-iso2usb"
uptodown-dlurl = "https://rufus-unofficial.en.uptodown.com/android"
