[Fdroid-patchweaver]
enabled = true
pkg-name = "org.fdroid.fdroid"
app-name = "F-Droid"
brand = "patchweaver"
patches-source = "ispacecase/patchweaver"
apkmirror-dlurl = "https://www.apkmirror.com/apk/f-droid-limited/f-droid"
apkpure-dlurl = "https://apkpure.com/f-droid/org.fdroid.fdroid"

