[GooglePhotos-DeVanced]
enabled = true
pkg-name = "com.google.android.apps.photos"
app-name = "Google Photos"
brand = "DeVanced"
build-mode = "both"
patches-version = "both"
patches-source = "RookieEnough/De-Vanced"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"

[GooglePhotos-rushiranpise]
enabled = true
pkg-name = "com.google.android.apps.photos"
app-name = "Google Photos"
brand = "rushiranpise"
patches-source = "rushiranpise/morphe-patches"
included-patches = "'AMOLED dark theme' 'Change package name' 'Enable DCIM folders backup control' 'Fix DCIM folder classification'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[GooglePhotos-AkashSriram]
enabled = true
pkg-name = "com.google.android.apps.photos"
app-name = "Google Photos"
brand = "AkashSriram"
build-mode = "both"
patches-source = "Akash-Sriram/morphe-google-photos"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[GooglePhotos-DeVanced-Experimental]
enabled = true
app-name = "Google Photos"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "com.google.android.apps.photos"
patches-source = "RookieEnough/De-Vanced"
brand = "DeVanced"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"

[GooglePhotos-rushiranpise-Experimental]
enabled = true
app-name = "Google Photos"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "com.google.android.apps.photos"
patches-source = "rushiranpise/morphe-patches"
brand = "rushiranpise"
included-patches = "'AMOLED dark theme' 'Change package name' 'Enable DCIM folders backup control' 'Fix DCIM folder classification'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[GooglePhotos-AkashSriram-Experimental]
enabled = true
app-name = "Google Photos"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "com.google.android.apps.photos"
patches-source = "Akash-Sriram/morphe-google-photos"
brand = "AkashSriram"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
