[GooglePhotos-DeVanced]
enabled = true
pkg-name = "com.google.android.apps.photos"
app-name = "Google Photos"
brand = "DeVanced"
build-mode = "both"
patches-version = "both"
patches-source = "RookieEnough/De-Vanced"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"

[GooglePhotos-rushiranpise]
enabled = true
pkg-name = "com.google.android.apps.photos"
app-name = "Google Photos"
brand = "rushiranpise"
patches-source = "rushiranpise/morphe-patches"
included-patches = "'AMOLED dark theme' 'Change package name' 'Enable DCIM folders backup control' 'Fix DCIM folder classification'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[GooglePhotos-AkashSriram]
enabled = true
pkg-name = "com.google.android.apps.photos"
app-name = "Google Photos"
brand = "AkashSriram"
build-mode = "both"
patches-source = "Akash-Sriram/morphe-google-photos"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"




