enable-module-update = true
patches-source = "crimera/piko"
patch-brand = "Piko"
cli-type = "morphe"

[Instagram-Morphe-Piko]
enabled = true
app-name = "Instagram"
arch = "arm64-v8a x86_64"
pkg-name = "com.instagram.android"
patcher-args = "--continue-on-error"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
apkmirror-example-url = "https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-439-0-0-37-89-release/"

# ── X (Twitter) morphe-piko (no material you) ─────────────────────────────────

[Twitter-Morphe-Piko]
enabled = true
app-name = "Twitter"
pkg-name = "com.twitter.android"
excluded-patches = "'Dynamic Color'"
patcher-args = "--continue-on-error"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"

# ── X (Twitter) morphe-piko-materialyou (Material You / Dynamic Color) ──────────

[Twitter-Morphe-Piko-Experimental]
enabled = true
app-name = "Twitter"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
pkg-name = "com.twitter.android"
excluded-patches = "'Dynamic Color'"
patcher-args = "--continue-on-error"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"

# ── X (Twitter) morphe-piko-materialyou (Material You / Dynamic Color) ──────────

[Twitter-Morphe-Piko-MaterialYou]
enabled = true
app-name = "Twitter"
variant = "MaterialYou"
pkg-name = "com.twitter.android"
included-patches = "'Dynamic Color'"
patcher-args = "--continue-on-error"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"

[Twitter-Morphe-Piko-MaterialYou-Experimental]
enabled = true
app-name = "Twitter"
variant = "MaterialYou"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
pkg-name = "com.twitter.android"
included-patches = "'Dynamic Color'"
patcher-args = "--continue-on-error"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
