[Pinterest-binarymend]
enabled = true
pkg-name = "com.pinterest"
app-name = "Pinterest"
patches-source = "binarymend/morphe-patches"
brand = "binarymend"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pinterest/pinterest-one-destination-for-a-world-of-inspiration"
uptodown-dlurl = "https://pinterest.en.uptodown.com/android"

[Pinterest-browzomje]
enabled = true
pkg-name = "com.pinterest"
app-name = "Pinterest"
patches-source = "browzomje/browzomje-patches"
brand = "browzomje"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pinterest/pinterest-one-destination-for-a-world-of-inspiration"
uptodown-dlurl = "https://pinterest.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/pinterest/com.pinterest"
apkcombo-dlurl = "https://apkcombo.com/pinterest/com.pinterest"
