patches-source = "PrathxmOp/Prathxm-Patches"
brand = "Prathxm"

[ChessDotCom-Prathxm]
enabled = true
app-name = "Chess.com"
version = "auto"
pkg-name = "com.chess"
uptodown-dlurl = "https://chess.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/chess-com/chess-play-learn/"
apkmirror-example-url = "https://www.apkmirror.com/apk/chess-com/chess-play-learn/chess-com-do-you-miss-us-4-10-6-googleplay-release/"

[ChessDotCom-Prathxm-Clone]
enabled = true
app-name = "Chess.com"
sub-variant = "Clone"
version = "auto"
pkg-name = "com.chess"
uptodown-dlurl = "https://chess.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/chess-com/chess-play-learn/"
apkmirror-example-url = "https://www.apkmirror.com/apk/chess-com/chess-play-learn/chess-com-do-you-miss-us-4-10-6-googleplay-release/"
included-patches = "'Clone Chess.com'"
