patches-source = "PrathxmOp/Prathxm-Patches"
brand = "Prathxm"

[ChessDotCom-Prathxm]
enabled = true
pkg-name = "com.chess"
app-name = "Chess.com"
apkmirror-dlurl = "https://www.apkmirror.com/apk/chess-com/chess-play-learn"
uptodown-dlurl = "https://chess-play-and-learn.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/chess-play-and-learn-online/com.chess"
apkcombo-dlurl = "https://apkcombo.com/chess/com.chess"


