[ProtonVPN-hoodles]
enabled = true
pkg-name = "ch.protonvpn.android"
app-name = "Proton VPN"
patches-source = "hoo-dles/morphe-patches"
brand = "hoodles"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/proton-vpn/ch.protonvpn.android"

[ProtonVPN-hoodles-Experimental]
enabled = true
pkg-name = "ch.protonvpn.android"
app-name = "Proton VPN"
patches-source = "hoo-dles/morphe-patches"
brand = "hoodles"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
patcher-args = "-f --continue-on-error"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/proton-vpn/ch.protonvpn.android"

[ProtonVPN-hxreborn]
enabled = true
pkg-name = "ch.protonvpn.android"
app-name = "Proton VPN"
patches-source = "hxreborn/morphe-patches"
brand = "hxreborn"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/proton-vpn/ch.protonvpn.android"

[ProtonVPN-hxreborn-Experimental]
enabled = true
pkg-name = "ch.protonvpn.android"
app-name = "Proton VPN"
patches-source = "hxreborn/morphe-patches"
brand = "hxreborn"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
patcher-args = "-f --continue-on-error"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/proton-vpn/ch.protonvpn.android"

[ProtonVPN-Paresh]
enabled = true
pkg-name = "ch.protonvpn.android"
app-name = "Proton VPN"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
brand = "Paresh"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/proton-vpn/ch.protonvpn.android"

[ProtonVPN-Paresh-Experimental]
enabled = true
pkg-name = "ch.protonvpn.android"
app-name = "Proton VPN"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
brand = "Paresh"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
patcher-args = "-f --continue-on-error"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/proton-vpn/ch.protonvpn.android"

[ProtonVPN-Rushiranpise]
enabled = true
pkg-name = "ch.protonvpn.android"
app-name = "Proton VPN"
patches-source = "rushiranpise/morphe-patches"
brand = "rushiranpise"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn/"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/proton-vpn/ch.protonvpn.android"

[ProtonVPN-Rushiranpise-Experimental]
enabled = true
pkg-name = "ch.protonvpn.android"
app-name = "Proton VPN"
patches-source = "rushiranpise/morphe-patches"
brand = "rushiranpise"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
patcher-args = "-f --continue-on-error"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn/"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/proton-vpn/ch.protonvpn.android"
