[ProtonMail-hxreborn]
enabled = true
pkg-name = "ch.protonmail.android"
app-name = "Proton Mail"
brand = "hxreborn"
patches-source = "hxreborn/morphe-patches"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/proton-mail-encrypted-email/ch.protonmail.android"
apkcombo-dlurl = "https://apkcombo.com/proton-mail/ch.protonmail.android"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"

[ProtonMail-hxreborn-Experimental]
enabled = true
pkg-name = "ch.protonmail.android"
app-name = "Proton Mail"
brand = "hxreborn"
patches-source = "hxreborn/morphe-patches"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
patcher-args = "-f --continue-on-error"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/proton-mail-encrypted-email/ch.protonmail.android"
apkcombo-dlurl = "https://apkcombo.com/proton-mail/ch.protonmail.android"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"

[ProtonMail-SatanMerde]
enabled = true
pkg-name = "ch.protonmail.android"
app-name = "Proton Mail"
patches-source = "SatanMerde/D-moniakPatches"
brand = "SatanMerde"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/proton-mail-encrypted-email/ch.protonmail.android"
apkcombo-dlurl = "https://apkcombo.com/proton-mail/ch.protonmail.android"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"

[ProtonMail-SatanMerde-Experimental]
enabled = true
pkg-name = "ch.protonmail.android"
app-name = "Proton Mail"
patches-source = "SatanMerde/D-moniakPatches"
brand = "SatanMerde"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
patcher-args = "-f --continue-on-error"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/proton-mail-encrypted-email/ch.protonmail.android"
apkcombo-dlurl = "https://apkcombo.com/proton-mail/ch.protonmail.android"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"

[ProtonMail-dhrubonai]
enabled = true
pkg-name = "ch.protonmail.android"
app-name = "Proton Mail"
patches-source = "dhrubonai/morphe-patches"
brand = "dhrubonai"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/proton-mail-encrypted-email/ch.protonmail.android"
apkcombo-dlurl = "https://apkcombo.com/proton-mail/ch.protonmail.android"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"

[ProtonMail-dhrubonai-Experimental]
enabled = true
pkg-name = "ch.protonmail.android"
app-name = "Proton Mail"
patches-source = "dhrubonai/morphe-patches"
brand = "dhrubonai"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
patcher-args = "-f --continue-on-error"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/proton-mail-encrypted-email/ch.protonmail.android"
apkcombo-dlurl = "https://apkcombo.com/proton-mail/ch.protonmail.android"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"

[ProtonMail-rushiranpise]
enabled = true
pkg-name = "ch.protonmail.android"
app-name = "Proton Mail"
patches-source = "rushiranpise/morphe-patches"
brand = "rushiranpise"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/proton-mail-encrypted-email/ch.protonmail.android"
apkcombo-dlurl = "https://apkcombo.com/proton-mail/ch.protonmail.android"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"

[ProtonMail-rushiranpise-Experimental]
enabled = true
pkg-name = "ch.protonmail.android"
app-name = "Proton Mail"
patches-source = "rushiranpise/morphe-patches"
brand = "rushiranpise"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
patcher-args = "-f --continue-on-error"
prefer-dl-mode = "bundle"
dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/proton-mail-encrypted-email/ch.protonmail.android"
apkcombo-dlurl = "https://apkcombo.com/proton-mail/ch.protonmail.android"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"
