[Reddit-Morphe]
enabled = true
pkg-name = "com.reddit.frontpage"
app-name = "Reddit"
patches-source = "MorpheApp/morphe-patches"
brand = "Morphe"
patches-version = "both"
build-mode = "both"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/reddit-app/com.reddit.frontpage"
apkcombo-dlurl = "https://apkcombo.com/reddit/com.reddit.frontpage"
archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"

[Reddit-Morphe-Experimental]
enabled = true
pkg-name = "com.reddit.frontpage"
app-name = "Reddit"
patches-source = "MorpheApp/morphe-patches"
brand = "Morphe"
patches-version = "both"
build-mode = "both"
variant = "Experimental"
version = "exp"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/reddit-app/com.reddit.frontpage"
apkcombo-dlurl = "https://apkcombo.com/reddit/com.reddit.frontpage"

[Reddit-adobo]
enabled = true
pkg-name = "com.reddit.frontpage"
app-name = "Reddit"
patches-source = "jkennethcarino/adobo"
brand = "adobo"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/reddit-app/com.reddit.frontpage"
apkcombo-dlurl = "https://apkcombo.com/reddit/com.reddit.frontpage"
archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"
