[Threads-chiggi]
enabled = true
pkg-name = "com.instagram.barcelona"
app-name = "Threads"
patch-folder = "threads"
patches-source = "durgesh0505/chiggi_morphe_patches"
brand = "chiggi"
arch = "arm64-v8a"
excluded-patches = "'Change app name' 'Change package name'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/threads-an-instagram-app"
uptodown-dlurl = "https://threads.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/threads-app/com.instagram.barcelona"

[Threads-chiggi-Clone]
enabled = true
pkg-name = "com.instagram.barcelona"
app-name = "Threads"
patch-folder = "threads"
patches-source = "durgesh0505/chiggi_morphe_patches"
brand = "chiggi"
variant = "Clone"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/threads-an-instagram-app"
uptodown-dlurl = "https://threads.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/threads-app/com.instagram.barcelona"

[Threads-HushThreads]
enabled = true
pkg-name = "com.instagram.barcelona"
app-name = "Threads"
patch-folder = "threads"
patches-source = "SysAdminDoc/HushThreads"
brand = "HushThreads"
arch = "arm64-v8a"
inclusive-patches = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/threads-an-instagram-app"
uptodown-dlurl = "https://threads.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/threads-app/com.instagram.barcelona"

