[Twitch-hooman]
enabled = true
pkg-name = "tv.twitch.android.app"
app-name = "Twitch"
patches-source = "arandomhooman/hoomans-morphe-patches"
brand = "hooman"
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"

[Twitch-ajstrick81-AndroidTV]
enabled = true
pkg-name = "tv.twitch.android.app"
app-name = "Twitch"
variant = "Android TV"
patches-source = "ajstrick81/morphe-androidtv-patches"
brand = "ajstrick81"
arch = "all arm64-v8a arm-v7a"
patch-folder = "twitchatv"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch-android-tv/"
apkpure-dlurl = "https://apkpure.com/twitch-livestream-multiplayer-games-esports-app/tv.twitch.android.app"
apkcombo-dlurl = "https://apkcombo.com/twitch/tv.twitch.android.app"

[Twitch-hooman-Experimental]
enabled = true
app-name = "Twitch"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "tv.twitch.android.app"
patches-source = "arandomhooman/hoomans-morphe-patches"
brand = "hooman"
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"

[Twitch-ajstrick81-AndroidTV-Experimental]
enabled = true
app-name = "Twitch"
variant = "Android TV"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
arch = "all arm64-v8a arm-v7a"
pkg-name = "tv.twitch.android.app"
patches-source = "ajstrick81/morphe-androidtv-patches"
brand = "ajstrick81"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch-android-tv/"
apkpure-dlurl = "https://apkpure.com/twitch-livestream-multiplayer-games-esports-app/tv.twitch.android.app"
apkcombo-dlurl = "https://apkcombo.com/twitch/tv.twitch.android.app"
