[Twitter-Piko]
enabled = true
pkg-name = "com.twitter.android"
app-name = "Twitter"
patches-source = "crimera/piko"
patches-version = "both"
build-mode = "both"
brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/x-formerly-twitter/com.twitter.android"

[Twitter-Piko-MaterialYou]
enabled = true
pkg-name = "com.twitter.android"
app-name = "Twitter"
variant = "Material You"
patches-source = "crimera/piko"
patches-version = "both"
build-mode = "both"
brand = "Piko"
included-patches = "'Bring back twitter' 'Dynamic color'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/x-formerly-twitter/com.twitter.android"


