[X-Piko]
enabled = true
pkg-name = "com.twitter.android"
app-name = "X"
patches-source = "crimera/piko"
brand = "Piko"
excluded-patches = "'Dynamic Color'"
patcher-args = "--continue-on-error"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
apkpure-dlurl = "https://apkpure.com/x-formerly-twitter/com.twitter.android"

[X-Piko-MaterialYou]
enabled = true
pkg-name = "com.twitter.android"
app-name = "X"
patches-source = "crimera/piko"
brand = "Piko"
variant = "Material You"
included-patches = "'Dynamic color'"
patcher-args = "--continue-on-error"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/x-formerly-twitter/com.twitter.android"

[X-Piko-Experimental]
enabled = true
pkg-name = "com.twitter.android"
app-name = "X"
patches-source = "crimera/piko"
brand = "Piko"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
excluded-patches = "'Dynamic Color'"
patcher-args = "-f --continue-on-error"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
apkpure-dlurl = "https://apkpure.com/x-formerly-twitter/com.twitter.android"

[X-Piko-MaterialYou-Experimental]
enabled = true
pkg-name = "com.twitter.android"
app-name = "X"
patches-source = "crimera/piko"
brand = "Piko"
variant = "Material You"
sub-variant = "Experimental"
version = "latest"
skip-patch-app-check = true
included-patches = "'Dynamic Color'"
patcher-args = "-f --continue-on-error"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
apkpure-dlurl = "https://apkpure.com/x-formerly-twitter/com.twitter.android"
