[YouTubeMusic-Morphe]
enabled = true
pkg-name = "com.google.android.apps.youtube.music"
app-name = "YouTube Music"
patches-source = "MorpheApp/morphe-patches"
brand = "Morphe"
patches-version = "both"
build-mode = "both"
patch-folder = "music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/youtube-music/com.google.android.apps.youtube.music"
apkcombo-dlurl = "https://apkcombo.com/youtube-music/com.google.android.apps.youtube.music"

[YouTubeMusic-Morphe-Experimental]
enabled = true
pkg-name = "com.google.android.apps.youtube.music"
app-name = "YouTube Music"
patches-source = "MorpheApp/morphe-patches"
brand = "Morphe"
sub-variant = "Experimental"
build-mode = "both"
arch = "arm64-v8a x86_64 armeabi-v7a x86"
version = "exp"
included-patches = "'Theme'"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
apkpure-dlurl = "https://apkpure.com/youtube-music/com.google.android.apps.youtube.music"
apkcombo-dlurl = "https://apkcombo.com/youtube-music/com.google.android.apps.youtube.music"

[YouTubeMusic-Morphe-AMOLED-Experimental]
enabled = true
pkg-name = "com.google.android.apps.youtube.music"
app-name = "YouTube Music"
patches-source = "MorpheApp/morphe-patches"
brand = "Morphe"
variant = "AMOLED"
sub-variant = "Experimental"
build-mode = "both"
arch = "arm64-v8a x86_64 armeabi-v7a x86"
version = "exp"
included-patches = "'Theme'"
patcher-args = "-OdarkThemeBackgroundColor=#000000"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
apkpure-dlurl = "https://apkpure.com/youtube-music/com.google.android.apps.youtube.music"
apkcombo-dlurl = "https://apkcombo.com/youtube-music/com.google.android.apps.youtube.music"

[YouTubeMusic-Anddea]
enabled = true
pkg-name = "com.google.android.apps.youtube.music"
app-name = "YouTube Music"
patches-source = "anddea/revanced-patches"
brand = "anddea"
build-mode = "both"
arch = "arm64-v8a x86_64 armeabi-v7a x86"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=@android:color/black --continue-on-error"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"

[YouTubeMusic-Anddea-AMOLED]
enabled = true
pkg-name = "com.google.android.apps.youtube.music"
app-name = "YouTube Music"
patches-source = "anddea/revanced-patches"
brand = "anddea"
variant = "AMOLED"
build-mode = "both"
arch = "arm64-v8a x86_64 armeabi-v7a x86"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=#000000 --continue-on-error"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
