[YouTube-Morphe]
enabled = true
pkg-name = "com.google.android.youtube"
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
brand = "Morphe"
build-mode = "both"
included-patches = "'Theme'"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
apkpure-dlurl = "https://apkpure.com/youtube-app/com.google.android.youtube"
apkcombo-dlurl = "https://apkcombo.com/youtube/com.google.android.youtube"

[YouTube-Morphe-AMOLED]
enabled = true
pkg-name = "com.google.android.youtube"
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
brand = "Morphe"
variant = "AMOLED"
build-mode = "both"
included-patches = "'Theme'"
patcher-args = "-OdarkThemeBackgroundColor=#000000 -OlightThemeBackgroundColor=#FFFFFF"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
apkpure-dlurl = "https://apkpure.com/youtube-app/com.google.android.youtube"
apkcombo-dlurl = "https://apkcombo.com/youtube/com.google.android.youtube"

[YouTube-Morphe-Experimental]
enabled = true
pkg-name = "com.google.android.youtube"
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
brand = "Morphe"
sub-variant = "Experimental"
build-mode = "both"
version = "exp"
included-patches = "'Theme'"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
apkpure-dlurl = "https://apkpure.com/youtube-app/com.google.android.youtube"
apkcombo-dlurl = "https://apkcombo.com/youtube/com.google.android.youtube"

[YouTube-Morphe-AMOLED-Experimental]
enabled = true
pkg-name = "com.google.android.youtube"
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
brand = "Morphe"
variant = "AMOLED"
sub-variant = "Experimental"
build-mode = "both"
version = "exp"
included-patches = "'Theme'"
patcher-args = "-OdarkThemeBackgroundColor=#000000 -OlightThemeBackgroundColor=#FFFFFF"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
apkpure-dlurl = "https://apkpure.com/youtube-app/com.google.android.youtube"
apkcombo-dlurl = "https://apkcombo.com/youtube/com.google.android.youtube"

[YouTube-Anddea]
enabled = true
pkg-name = "com.google.android.youtube"
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
brand = "anddea"
build-mode = "both"
included-patches = "'MaterialYou'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black --continue-on-error"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"

[YouTube-Anddea-AMOLED]
enabled = true
pkg-name = "com.google.android.youtube"
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
brand = "anddea"
variant = "AMOLED"
build-mode = "both"
included-patches = "'MaterialYou'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#000000 -OlightThemeBackgroundColor=#FFFFFF --continue-on-error"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"

[YouTube-Anddea-Experimental]
enabled = true
app-name = "YouTube"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "com.google.android.youtube"
patches-source = "anddea/revanced-patches"
brand = "anddea"
included-patches = "'MaterialYou'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Anddea-AMOLED-Experimental]
enabled = true
app-name = "YouTube"
variant = "AMOLED"
sub-variant = "Experimental"
version = "latest"
patcher-args = "-f --continue-on-error"
skip-patch-app-check = true
pkg-name = "com.google.android.youtube"
patches-source = "anddea/revanced-patches"
brand = "anddea"
included-patches = "'MaterialYou'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
