name: Update Website

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: website
  cancel-in-progress: true

jobs:
  rebuild_catalog:
    uses: ./.github/workflows/rebuild-catalog.yml
    secrets: inherit
